site_name: InfoSec App for Splunk Documentation

nav:
  - Home: "README.md"
  - "Introduction": "Introduction.md"
  - "Concepts": "docs/Concepts.md"
  - "Installation": "docs/3 - Installation.md"
  - "Configuration": "docs/4 - Configuration.md"
  - "Using the InfoSec App for Splunk": "docs/5 - UsingInfoSec.md"
  - "Support and Troubleshooting": "docs/6 - Support.md"

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite

theme:
  name: "material"
  palette:
    primary: "black"
    accent: "orange"
  favicon: "logo.png"
  logo: "logo.png"
